language: ruby
rvm:
  - 2.1.5
  - 2.1.7
  - 2.2.2
  - 2.2.3
  - 2.3.0
script:
  - bundle exec rubocop lib
  - bundle exec rubocop spec
  - bundle exec rubocop examples
  - bundle exec rubocop benchmarks
  - bundle exec rspec spec
